= TodoAndroid

This is the TodoMore Android client.

== Unfinished Warning

As of today it works fine as a local (on-device) To-do list manager.  The
Synch Adapter part is barely working, but don't use it unless you (a) have
a backup and (b) can code the parts that are missing.  The SyncAdapter
works, but neither end deletes the other end's deletions.  And, conflicts
aren't detected yet.

Next up in this area will be a delete feature; Right now delete is local
only. Delete does remove locally AND queue deletions, so the plan is to have
the sync adapter rm them remotely via REST before getting a list of the
"rest" of the remote todo's.

== Security Warning

This version caches your password, unencrypted, in the shared preferences.
Somebody who finds your phone AND knows what they're doing could modify
or corrupt your TODO listings.

Please fix this and send a pull request!

== Sync Adapter

There are several good tutorials and troubleshooting pages.
The official tutorial is at http://developer.android.com/training/sync-adapters/index.html.
A good note on some important details is at
http://stackoverflow.com/questions/5253858/why-does-contentresolver-requestsync-not-trigger-a-sync
