= TodoAndroid

This is the TodoMore Android client.

== Unfinished Warning

As of today it works fine as a local (on-device) To-do list manager.
The Synch Adapter part is close to working, but don'to use it unless you (a) have a backup and 
(b) can code the parts that are missing.
The SyncAdapter starts running but hasn't been tested end-to-end yet, so don't run it against
a database of real TODOs, unless you have a backup.

Next up in this area will be a delete feature; it's harder because you have to atomically commit 
in two places, and you can't (unless you implement full JDBC and a distributed transaction
manager...). Right now delete is local only. Plan is to delete locally AND queue deletions,
and have the sync adapter rm them remotely via REST before getting a list of the "rest" of the 
remote todo's.

== Security Warning

This version caches your password, unencrypted, in the shared preferences.
Somebody who finds your phone AND knows what they're doing could modify
or corrupt your TODO listings.

Please fix this and send a pull request!

== Sync Adapter

There are several good tutorials and troubleshooting pages.
The official tutorial is at http://developer.android.com/training/sync-adapters/index.html.
A good note on some important details is at
http://stackoverflow.com/questions/5253858/why-does-contentresolver-requestsync-not-trigger-a-sync
